name: augusta
channels:
  - defaults
  - pytorch
dependencies:
  - python=3.6
  - numpy
  - pytorch=1.0.0
  - pyzmq
  - torchvision
  - pip:
    - gym==0.11
    - pyyaml
    - click
    - ipython
    - tensorboardX
    - tensorflow
    - seaborn
