comment: template config
env-name: CrossRoom-v0
num-steps: 2
max-iter: 10000000
iter-per-eval: 1000
samples-for-eval: 1000
seed: 1234
force-cpu: true
train-score: true
train-source-distr: true
diverg-name: kl
batch-size: 1
hidden-size: 64
memory-size: 10000
score-lr: 0.001
score-momentum: 0.0
score-optim-name: adam
source-distr-lr: 0.001
source-distr-momentum: 0.0
source-distr-optim-name: adam
