comment: template config
env-name: CrossRoom-v0
num-steps: 2
max-iter: 10000000
# iter-per-eval: 1000
iter-before-train: 5000
seed: 1234
force-cpu: true
diverg-name: kl
batch-size: 64
hidden-size: 64
memory-size: 10000
lr: 0.001
momentum: 0.0
optim-name: adam
